// apps/nakita628-react-tanstack-todo/src/routes/index.tsx
import { Link, createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/')({
  component: Home,
})

function Home() {
  return (
    <div className='py-12 px-4'>
      <div className='max-w-2xl mx-auto text-center'>
        <h1 className='text-4xl font-bold text-gray-800 mb-4'>Todo App</h1>
        <p className='text-gray-600 mb-8'>Built with TanStack Router + TanStack Query</p>
        <Link
          to='/todos'
          className='inline-block bg-blue-500 hover:bg-blue-600 text-white font-semibold px-6 py-3 rounded-lg transition-colors'
        >
          View Todos
        </Link>
      </div>
    </div>
  )
}

// apps/nakita628-sveltekit-todo/src/routes/+page.svelte
<div class="py-12 px-4">
  <div class="max-w-2xl mx-auto text-center">
    <h1 class="text-4xl font-bold text-gray-800 mb-4">Todo App</h1>
    <p class="text-gray-600 mb-8">Built with SvelteKit + Svelte Query</p>
    <a
      href="/todos"
      class="inline-block bg-green-500 hover:bg-green-600 text-white font-semibold px-6 py-3 rounded-lg transition-colors"
    >
      View Todos
    </a>
  </div>
</div>
