// apps/nakita628-sveltekit-todo/src/routes/+page.svelte
<div class="py-12 px-4">
  <div class="max-w-2xl mx-auto text-center">
    <h1 class="text-4xl font-bold text-gray-800 mb-4">Todo App</h1>
    <p class="text-gray-600 mb-8">Built with SvelteKit + Svelte Query</p>
    <a
      href="/todos"
      class="inline-block bg-green-500 hover:bg-green-600 text-white font-semibold px-6 py-3 rounded-lg transition-colors"
    >
      View Todos
    </a>
  </div>
</div>

// apps/nakita628-react-router-swr-todo/src/routes/index.tsx
import { Link } from 'react-router'

export function HomePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 to-amber-100 flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-5xl font-bold text-gray-800 mb-4">
          Hono🔥 + SWR
        </h1>
        <p className="text-gray-600 text-lg mb-8">
          Todo App with React Router & SWR + Kysely
        </p>
        <Link
          to="/todos"
          className="inline-block bg-orange-500 hover:bg-orange-600 text-white font-semibold px-8 py-4 rounded-xl transition-colors shadow-lg hover:shadow-xl"
        >
          View Todos →
        </Link>
      </div>
    </div>
  )
}
